icu.hilin.freeswitch:
  enabled: true
  server:
    host: 192.168.2.20
    port: 8021
    password: ClueCon
    timeout: 10
    heartbeatExpire: 30
  inbound:
  outbound:
logging:
  level:
    "icu.hilin.cti.freeswitch.handler.biz.listener": warn